version:  '3.8'
services: 
  db:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cursomc_db
    ports:
      - 3306:3306
    volumes:
      - cursomc:/var/lib/mysql

volumes:
  cursomc: